#!/bin/bash
# ---- Aliases ----
alias gp="git push"
alias gs="git status"
alias ga="git add"
alias gaa="git add --all"
alias gcb="git checkout -b"
alias gco="git checkout"
alias gc="git commit -v"
alias gca="git commit -v -a"
alias gcam="git commit -a -m"
alias gl="git pull"
alias glg="git log --stat"
alias glgg="git log --graph"
alias glog="git log --oneline --decorate --graph"
alias gd="git diff"
alias gds="git diff --staged"
alias gf="git fetch"
